backend:
  name: github
  repo: 7h3kn0w3r/7h3kn0w3r.github.io
  branch: main
  base_url: https://zero-trust-git-main-sasas-projects-d455520b.vercel.app
  auth_endpoint: api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Dossier Writeups"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
